### ISSUE TITLE
Navigation CSS Glitch on long post load

### ISSUE THREAD

**Issue by anthhelm-math** [heiswayi/thinkspace#15]
When a long post is loaded, such as Markdown Cheatsheet Demo, the nav bar moves slightly to the left. Nav bar horizontal location is not constant, and depends on length of post being displayed.

**Comment by heiswayi** [comment]
I think that is due to your browser scrollbar and it's normal. When you're viewing the long post, the browser scrollbar will appear, and this makes it looked like it's moving slightly to the left. For non-overflow view... you won't see the browser scrollbar.
