### ISSUE TITLE
Bundler problem

### ISSUE THREAD

**Issue by denmarkgit** [heiswayi/thinkspace#25]
Bundler could not find compatible versions for gem "bundler":
  In Gemfile:
    bundler (~> 1.15)

  Current Bundler version:
    bundler (2.0.1)

**Comment by jignyasi** [comment]
Edit Line 17 in thinkspace.gemspec to 

`spec.add_development_dependency "bundler", "~> 2.0.1"`

This should solve your error

**Comment by denmarkgit** [comment]
thank you, sorry, still learning it
