### ISSUE TITLE
Comments false in post not working

### ISSUE THREAD

**Issue by Sulexa** [heiswayi/thinkspace#27]
Hi, 
Just tried out your template and I like it.
The only problem I have is, if I set `comments: false` inside a post it doesn't hide the comments section.
I had to change the first line in _includes/comments.html
from 
`{% if site.comments_enabled %}`
to
`{% if site.comments_enabled and page.comments %}`
And now it works has intended.

**Comment by heiswayi** [comment]
Thanks! I have fixed it.
